### ISSUE TITLE
KB Rubberbanding Glitch On PR Factions

### ISSUE THREAD

**Issue by SirStego** [PureRealms/Issues#18]
When you get hit by a kb sword, it makes you take no kb. This glitch gives an advantage to the person who's using the kb sword since they get more hits, when the opponent who is given the kb 2 tries to potion or gapple sometimes they will glitch and not work, resulting in an unfair win. This glitch makes you rubberband back to where you just were (if you're trying to run) and makes your screen see ridiculous block lag.

**Comment by FatherSouth** [comment]
Will be fixed on next restart
